#!/bin/bash

echo ""
echo "Album: 💋🚗🍷🍂 Red 🍂🍷🚗💋"
sleep 1
echo ""
echo "Released: October 22, 2012"
echo "Taylor's Version Released: November 12, 2021"
sleep 2

echo ""
echo "Tracklist:"
echo "1) State of Grace"
echo "2) Red"
echo "3) Treacherous"
echo "4) I Knew You Were Trouble"
echo "5) All Too Well"
echo "6) 22"
echo "7) I Almost Do"
echo "8) We Are Never Ever Getting Back Together"
echo "9) Stay Stay Stay"
echo "10) The Last Time (feat. Gary Lightbody)"
echo "11) Holy Ground"
echo "12) Sad Beautiful Tragic"
echo "13) The Lucky One"
echo "14) Everything Has Changed (feat. Ed Sheeran)"
echo "15) Starlight"
echo "16) Begin Again"
echo "17) The Moment I Knew"
echo "18) Come Back... Be Here"
echo "19) Girl at Home"
echo "20) Ronan"
sleep 1

echo ""
echo "From the Vault:"
echo "21) Better Man"
echo "22) Nothing New (feat. Phoebe Bridgers)"
echo "23) Babe"
echo "24) Message in a Bottle"
echo "25) I Bet You Think About Me (feat. Chris Stapleton)"
echo "26) Message in a Bottle"
echo "27) I Bet You Think About Me (feat. Chris Stapleton)"
echo "28) Forever Winter"
echo "29) Run (feat. Ed Sheeran)"
echo "20) The Very First Night"
echo "31) All Too Well (10 Minute Version)"
sleep 1

echo ""
read -p "Press enter to return to the main menu..."